In [48]:
import numpy as np

Linear Algebra refresher for ml

Vextor operations

In [49]:
u = np.arange(1,5).reshape(1, -1)
v = np.arange(1,5).reshape(-1,1)

v

array([[1],
       [2],
       [3],
       [4]])

In [50]:
def vector_vector_multiplications(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    return result
    

In [51]:
u.dot(v)

array([[30]])

Matrix-vector multiplication

In [52]:
U = np.array([
    [2,4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U


array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [53]:
V = np.array([
    [1,1, 2],
    [2,3,5],
    [4,2,9],
    [3,4,6]
])
V

array([[1, 1, 2],
       [2, 3, 5],
       [4, 2, 9],
       [3, 4, 6]])

In [54]:
def matrix_vector_mulitplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] =vector_vector_multiplications(U[i], v)
    
    return result
    

In [55]:
matrix_vector_mulitplication(U, v)

/tmp/ipykernel_2075/485396606.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result[i] =vector_vector_multiplications(U[i], v)


array([49., 16., 15.])

Matrix-matrix multiplication

In [56]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mulitplication(U, vi)
        result[:, i] = Uvi
    return result
        
    

In [57]:
matrix_matrix_multiplication(U, V)

array([[ 48.,  48., 105.],
       [ 15.,  17.,  33.],
       [ 16.,  14.,  35.]])

In [58]:
U.dot(V)

array([[ 48,  48, 105],
       [ 15,  17,  33],
       [ 16,  14,  35]])

In [59]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Inverse

In [61]:
Vs = V[[0,1,2]]
Vs

array([[1, 1, 2],
       [2, 3, 5],
       [4, 2, 9]])

In [62]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 5.66666667, -1.66666667, -0.33333333],
       [ 0.66666667,  0.33333333, -0.33333333],
       [-2.66666667,  0.66666667,  0.33333333]])

In [64]:
i_matrix = Vs.dot(Vs_inv)
i_matrix

array([[ 1.00000000e+00, -2.22044605e-16, -1.11022302e-16],
       [ 1.33226763e-15,  1.00000000e+00, -1.66533454e-16],
       [ 1.33226763e-15, -3.33066907e-16,  1.00000000e+00]])