In [1]:
import pandas as pd
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
a = np.array([1,2,3,5,6,7])
a

array([1, 2, 3, 5, 6, 7])