In [10]:
import pandas as pd
import numpy as np

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
a = np.array([1,2,3,5,6,7])
a

array([1, 2, 3, 5, 6, 7])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n = np.array([[1,2,3],
              [4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
n[:, 2]

array([3, 6])

In [18]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

Element-wise operations

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
a + 1

array([1, 2, 3, 4, 5])

In [ ]:

(10 + ((a *  2)) ** 2)

array([10, 14, 26, 46, 74])

Comparison Operations

In [23]:
a >= 2

array([False, False,  True,  True,  True])